services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: pqdb
    networks:
      - db_nw
    environment:
      POSTGRES_PASSWORD: Passw0rd!

  app:
    build: .
    ports:
      - "8989"
    networks:
      - db_nw
      - app_nw
      - redis_nw
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
    networks:
      - app_nw
    depends_on:
      - app

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - redis_nw

volumes:
  redis:

networks:
  db_nw:
    driver: bridge
  app_nw:
    driver: bridge
  redis_nw:
    driver: bridge
