name: Deploy Staging

# Test
on: push

# on:
#   push:
#     branches:
#       - staging

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2

      # see: https://zenn.dev/kt3k/articles/d557cc874961ab
      - name: Restore mtime
        run: python ./.github/utils/git-restore-mtime.py

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose
