name: Deploy Staging

# Test
on: push

# on:
#   push:
#     branches:
#       - staging

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
